// Copyright 2023 The Falco Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package events

import "github.com/alacuku/k8s-metadata/internal/fields"

// Event interface that must be satisfied by events generated for each supported k8s resource.
// Evens are generated by the collectors and sent to the message broker which is in charge to
// deliver them to all subscribers that have an interest for those events.
type Event interface {
	Nodes() fields.Nodes
	String() string
}
