apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: meta-collector
    app.kubernetes.io/component: meta-collector
    app.kubernetes.io/created-by: manifests
  name: meta-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-collector
  namespace: meta-collector
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: meta-collector
    app.kubernetes.io/component: meta-collector
    app.kubernetes.io/created-by: manifests
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: meta-collector
      app.kubernetes.io/component: meta-collector
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/instance: meta-collector
        app.kubernetes.io/component: meta-collector
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /meta-collector
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              name: "metrics"
            - containerPort: 8081
              name: "health-probe"
            - containerPort: 45000
              name: "broker-grpc"
          image: docker.io/falcosecurity/k8s-metacollector:latest
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: meta-collector
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: meta-collector
    app.kubernetes.io/component: meta-collector
    app.kubernetes.io/created-by: manifests
  name: meta-collector
  namespace: meta-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: meta-collector
    app.kubernetes.io/component: meta-collector
    app.kubernetes.io/created-by: manifests
  name: meta-collector-role
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
      - namespaces
      - pods
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: meta-collector
    app.kubernetes.io/component: meta-collector
    app.kubernetes.io/created-by: manifests
  name: meta-collector-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meta-collector-role
subjects:
  - kind: ServiceAccount
    name: meta-collector
    namespace: meta-collector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: meta-collector
    app.kubernetes.io/component: meta-collector
    app.kubernetes.io/created-by: manifests
  name: meta-collector
  namespace: meta-collector
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
    - name: health-probe
      port: 8081
      protocol: TCP
    - name: broker-grpc
      port: 45000
      protocol: TCP
  selector:
    app.kubernetes.io/instance: meta-collector
    app.kubernetes.io/component: meta-collector
